# .sqa/config.yml - jenkins-pipeline-library configuration file

# generic configuration: workspace, agents
config:
  project_repos:
    bench_api:
      repo: 'https://github.com/inab/bench_event_api.git'
      branch: jenkins
      #dockerhub: worsica/worsica-processing
      #dockertag: $branch

sqa-criteria:
  qc_style:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api/tox.ini
          testenv:
            - pep8
  qc_security:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api/tox.ini
          testenv:
            - bandit
  qc_coverage:
    repos:
      bench_api:
        container: processing
        tox:
          tox_file: /bench_event_api/tox.ini
          testenv: 
            - cover
            - cobertura

environment:
  GIT_COMMITTER_NAME: javi-gv94
  GIT_COMMITTER_EMAIL: javier.garrayo@hotmail.com
  LANG: C.UTF-8

timeout: 600